Added RoboSub post
ut-ras/ras_site_old pull request #49
Opened 2020-02-15 01:22 UTC by jspspike

2020-02-15 02:13 UTC, rrbutani commented on _includes/header.html
> +                <a class="dropdown-item" href="{{ site.baseurl }}/about/curm.html">CURM</a>
@jspspike I think this was a mistake

2020-02-15 02:24 UTC, jspspike commented on _includes/header.html
> +                <a class="dropdown-item" href="{{ site.baseurl }}/about/curm.html">CURM</a>
Oops, fixed now

2020-02-15 19:38 UTC, rrbutani approved these changes

2020-02-19 00:25 UTC, RosannaR requested changes
There is an issue with line 16.

2020-02-19 03:38 UTC, jspspike commented
> There is an issue with line 16.
Removed that line

2020-02-19 17:37 UTC, RosannaR approved these changes

2020-02-19 18:16 UTC, merged